[project]
name = "TeSS-Metadata-Extractor-Agent"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "Kenneth", email = "kenneth.brian.rioja@cern.ch"},
]
dependencies = ["crawl4ai>=0.8.6", "openai>=2.36.0", "python-dotenv>=1.2.2", "pyyaml>=6.0.3", "pydantic>=2.13.4"]
requires-python = ">=3.12.*,<3.14"
readme = "README.md"
license = {text = "CC-4.0"}


[tool.pdm]
distribution = false

[dependency-groups]
dev = [
    "requests>=2.33.1",
    "bs4>=0.0.2",
]
